# -*- coding: utf-8 -*-
"""Lab1AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oWJ-pbso_6s4TB6A2G421nh4s-CrWt_W
"""

print("Jawad Jan")
a=5
b=6

"""**Addition**"""

a+b

"""**Division**"""

a/b

"""**Multiplication**"""

a*b

"""**Subtraction**"""

a-b

"""**Jawad** **Jan**"""