# -*- coding: utf-8 -*-
"""Lab1AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h69BUwAoCGR0YWsvfU4RJTqtefAI28qQ

This code prints my name with initializing two variables of int type i.e "a" and "b"
"""

print("Jawad Jan")
a=5
b=6

"""**Addition**

This code adds two variables already initialized with value i.e "a" and "b"
"""

a+b

"""**Division**

This code Divides two variables already initialized with value i.e "a" and "b"
"""

a/b

"""**Multiplication**

This code Multiplies two variables already initialized with value i.e "a" and "b"
"""

a*b

"""**Subtraction**

This code subtracts two variables already initialized with value i.e "a" and "b"
"""

a-b

"""**Jawad** **Jan**

This is a simple name written of me told by Mam!
"""