# -*- coding: utf-8 -*-
"""Labtask2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DkvJdtXuyCAaVJghXnf5jP8B2AQb2HNg

**Matplotlib**

**Numpy**

**List**
"""

list = [14,28,34,4,32,34,98,50,9,10]
sum = 0
for num in list:
  print(num)
  sum+=num
print("Sum:",sum)
print("Maximum:",max(list))
print("Minimum:",min(list))
print("Ascending:",sorted(list))
print("Descending",sorted(list,reverse=True))

"""**Tuple**"""

mobiles= ("Samsung","Iphone","Xiaomi","Oppo","Vivo")
print("2nd element:",mobiles[1])
print("Last element:",mobiles[-1])
new_mobiles = list(mobiles)
print("New",new_mobiles)

"""**Set**"""

set1 = {23,4,66,88,44,8,878,676}
set2 = {34,45,68,6,23,4,54,765,87,43634,536,3,43,66,23}
print("Union:",set1.union(set2))
print("Intersection:",set1.intersection(set2))
set1.add(75)
set2.remove(765)
print("Set1:",set1)
print("Set2:",set2)

"""**Dictionary**"""

student = {"Name":"Jawad", "CGPA" : 3.91, "Roll no.":113, "Age": 22}
print(student)
student.update({"Age": 23})
print(student)